feat: integrate github oauth
profianinc/benefice pull request #11
Opened 2022-06-23 13:59 UTC by definitelynobody

2022-06-29 17:03 UTC, rvolosatovs commented
Please rebase on latest `main` :)

2022-07-01 09:11 UTC, rvolosatovs requested changes
Please rebase on latest `main` and follow the description in https://github.com/profianinc/benefice/issues/6, the process is explained there step-by-step with references to relevant documentation and copy-pastable code.
I do not understand how this relate to the issue at hand and I am happy to jump on a call to discuss what this should do.

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +//////////////////////// TODO
What is this for?

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +pub const LOGIN_URI: &str = "/auth/auth0";
```suggestion
pub const LOGIN_URI: &str = "/login";
```

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +pub const LOGOUT_URI: &str = "/auth/auth0/logout";
```suggestion
pub const LOGOUT_URI: &str = "/logout";
```

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +// pub const AUTHORIZED_URI: &str = "/auth/auth0/authorized";
```suggestion
```

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +    let res = ureq::get("https://api.github.com/user")
This should be doing a `UserInfo` request using the configured OIDC client https://github.com/profianinc/drawbridge/blob/bb43cb593f04030b376143bfe55476f06da025fc/crates/app/src/auth/oidc.rs#L94-L113

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +        let token_url = format!("https://{}/oauth/token", auth0_host);
What are these for? Why are `/login`, `/logout` and `/authorized` not enough?

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/auth0/mod.rs
> +                RedirectUrl::new(format!("http://{}{}", host, AUTHORIZED_URI)).unwrap(),
We should host this on https and never redirect to `http`

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/github/mod.rs
Github provider can be completely removed

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/mod.rs
>  pub mod github;
```suggestion
```

2022-07-01 09:11 UTC, rvolosatovs commented on crates/auth/src/providers/mod.rs
>      GitHub,
```suggestion
```

2022-07-05 13:31 UTC, npmccallum commented
@definitelynobody This is blocking other important features and needs to be pushed over the line ASAP.

2022-07-05 20:10 UTC, closed without merging