feat: allow drawbridge sourced toml files to be editable
profianinc/benefice pull request #114
Opened 2022-08-03 21:18 UTC by definitelynobody

If the toml file was not changed or couldn't be read then 'enarx deploy' will be used instead.

The only change the user will see with this change is that the config is always editable.

2022-08-08 10:29 UTC, rvolosatovs requested changes

2022-08-08 10:29 UTC, rvolosatovs commented on src/jobs.rs
> +    pub async fn new<'a>(
Is it really `async`? Is the lifetime used anywhere?

2022-08-08 10:29 UTC, rvolosatovs commented on src/jobs.rs
> +                            .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response())?
These errors will be impossible to debug in production settings. How about we don't discard the error, but rather log it?
Something like this:
```suggestion
                            .map_err(|e| {
                            	warn!("failed to fetch Wasm: {e}"); // or debug!, error!, whichever is appropriate
                            	StatusCode::INTERNAL_SERVER_ERROR.into_response()
                            })?
```

2022-08-08 10:29 UTC, rvolosatovs commented on src/jobs.rs
> +                            .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response())?;
Are these errors really Internal Server Errors? Isn't the slug user input?

Internal Server Errors are only for when the Benefice server itself has an issue (e.g. a bug or it instance ran out of space and could not create a temporary file)

2022-08-08 10:29 UTC, rvolosatovs commented on src/jobs.rs
> +                        wasm = Some(new_wasm);
Instead of mutating `wasm`, return it from the `match`

2022-08-08 10:29 UTC, rvolosatovs commented on src/main.rs
> +async fn enarx_toml_fallback<'a>(
When is this called? Can we add some docs?

What is the `'a` lifetime for?

2022-08-09 15:11 UTC, definitelynobody commented
I will make these changes and apply them in #118

2022-08-18 14:47 UTC, closed without merging